### ISSUE TITLE
CSS

### ISSUE THREAD

**Issue by ghost** [Stratus211/prj-rev-bwfs-dasmoto#6]
https://github.com/Stratus211/prj-rev-bwfs-dasmoto/blob/master/Dasmoto/resources/style.css#L13-L36

There's way too much repetition here. Use more general selectors, like `h2`, so that you can consolidate shared styles in one location and keep your CSS tidy and maintainable.

If you'd used `div` tags with the same class and `h2` tags with different IDs, you could write the following selectors which are more specific than just `h2`, but also more readable and concise.

```css
.product h2 {
  font-size: 32px;
  font-weight: bold;
  color: white;
}

#brushes {
  background-color: mediumspringgreen;
}
```
